name: Selenium Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Build with Maven
      run: mvn clean install
      env:
        DISPLAY: ':99.0'

    - name: Run Selenium Tests
      run: mvn test
      env:
        DISPLAY: ':99.0'
        _JAVA_OPTIONS: '-Dwebdriver.chrome.driver=/usr/bin/google-chrome'
